---
- name: Add coreos helm repository
  become: yes
  become_user: "{{ k8user }}"
  shell: helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/ > grafana.coreos.added
  args:
    chdir: $HOME
    creates: grafana.coreos.added

- name: Install prometheus operator
  become: yes
  become_user: "{{ k8user }}"
  shell: helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring > grafana.prometheus.installed
  args:
    chdir: $HOME
    creates: grafana.prometheus.installed

- name: Install kube prometheus
  become: yes
  become_user: "{{ k8user }}"
  shell: helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring > grafana.rbac.set
  args:
    chdir: $HOME
    creates: grafana.rbac.set
