---


# - hosts: k8s-cluster
#   gather_facts: True
#   pre_tasks:
#     - name: gather facts from all instances
#       setup:
#       delegate_to: "{{item}}"
#       delegate_facts: True
#       with_items: "{{ groups['k8s-cluster'] }}"
#   tasks:
#     - debug:
#         var: hostvars[inventory_hostname]

# - hosts: etcd
#   become: true
#   roles:
#   - role: etcd
#     etcd_hosts: '{{ groups["etcd"] }}'






- hosts: k8s-minion
  gather_facts: False
  roles:
  - { role: k8s-minion, tags: ["join"]}


