---
# This playbook contains common plays that will be run on all nodes.

- name: install kubectl
  become: yes
  apt:
    name: kubectl
    state: present

- name: copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ k8user }}/.kube/config"
    remote_src: yes
    owner: "{{ k8user }}"
