---
- name: Initialize the cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster.initialized
  args:
    chdir: $HOME
    creates: cluster.initialized

- name: Copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ k8user }}/.kube/config"
    remote_src: yes
    owner: "{{ k8user }}"

- name: Get join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Check addons directories
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'