---
- name: Enable passing bridged IPv4 traffic to iptables’ chains
  shell: sysctl net.bridge.bridge-nf-call-iptables=1

- name: Install pod network addon
  become: yes
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - flannel.yaml

- name: install Pod network
  become: yes
  become_user: '{{ k8user }}'
  shell: kubectl apply -f {{ k8s_addons_dir }}/flannel.yml >> pod_network.setup
  args:
    chdir: $HOME
    creates: pod_network.setup
