- name: Ensure Python 3 tools are installed
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - python

- name: Determine running python version
  block:
    - command: python --version
      register: python_version
    - debug:
        msg: "Running python {{ python_version.stdout }}"

- name: Fail if python is not 3.7
  fail:
    msg: "Python 3.7 is required. Currently in use: {{ python_version.stdout }}"
  when: python_version.stdout != "Python 3.7.0"