---
- name: Ensure required packages are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - software-properties-common
    - curl

- name: Add Docker apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get os release
  shell: . /etc/os-release; echo "$ID"
  register: os

- name: Get lsb release
  shell: lsb_release -cs
  register: lsb

- name: Set os_release
  set_fact: 
    os_release: "{{ os.stdout }}"

- name: Set lsb release
  set_fact: 
    lsb_release: "{{ lsb.stdout }}"

- name: Add Docker APT repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ os_release }} {{ lsb_release }} stable"
    state: present
    filename: 'docker'

- name: Get available Docker version
  shell: apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}'
  register: docker_version_cmd

- name: Set docker version
  set_fact: 
    docker_version: "{{ docker_version_cmd.stdout }}"

- name: Install Docker
  become: yes
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    update_cache: true


# - debug: msg="trigger nginx-restart"
#   notify: restart docker
#   changed_when: true


